name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: echo $GITHUB_REPOSITORY
      - run: yarn
      - name: remove fs dep from lib
        run: ls node_modules/postman-to-openapi/lib
      - name: sed1
        run: sed -i 's/const { promises:/\/\//' node_modules/postman-to-openapi/lib/index.js  > temp.js
      - name: sed2  (cp)
        run: cp temp.js node_modules/postman-to-openapi/lib/index.js
      - run: yarn test
      - name: Build
        run: yarn build
